# Generated by Django 3.0.3 on 2020-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201211_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='accounts/profile_pics/user.png', null=True, upload_to='accounts/profile_pics'),
        ),
    ]
